package com.testexample.approval.budgetapproval;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ApproverEvaluation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "APPROVEREVALUATION_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "APPROVEREVALUATION_ID_SEQ", name = "APPROVEREVALUATION_ID_GENERATOR")
   private java.lang.Long id;

   private java.lang.String comment;

   private java.lang.Boolean approved;

   public ApproverEvaluation()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getComment()
   {
      return this.comment;
   }

   public void setComment(java.lang.String comment)
   {
      this.comment = comment;
   }

   public java.lang.Boolean getApproved()
   {
      return this.approved;
   }

   public void setApproved(java.lang.Boolean approved)
   {
      this.approved = approved;
   }

   public String setProjectApproval(String userName) throws SQLException
   {
      ProjectEvaluation pr = new ProjectEvaluation();
      DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
      Date date = new Date();
      System.out.println(dateFormat.format(date));
      // System.out.println("userName"+userName);
String str1;
str1=userName;
			System.out.println(str1);
        String [] arr = str1.split(":");

      Connection c = null;
      Statement stmt = null;
      ResultSet rs = null;
      System.out.println("HI  : ");
    //  System.out.println("applicant.getProject() : " + applicant.getProject() + "applicant.getDescription() : " + applicant.getDescription() + "applicant.getFundValueRequisted() : " + applicant.getFundValueRequisted());
      //  System.out.println("org driver class");
      try
      {
         int project_Id = 0;
         Class.forName("org.postgresql.Driver");
         System.out.println("Before  Driver");
         c = DriverManager.getConnection("jdbc:postgresql://localhost:5432/mytest", "postgres", "espl@2017");
        // String str1 = getApplicant().toString();
        // System.out.println("str1" + str1);
         stmt = c.createStatement();
         String sql1 = "(SELECT project_Id from PROJECT_EVALUATION WHERE project='" + arr[1] + "' AND description='" +  arr[2] + "'AND requisted_fundvalue=" +  arr[3]+ ")";
         System.out.println("Select Project Approval" + sql1);
         rs = stmt.executeQuery(sql1);

         while (rs.next())
         {
            project_Id = rs.getInt("project_Id");
         }

         System.out.println("project_Id" + project_Id);
         String sql = "INSERT INTO PROJECT_APPROVER_STATUS VALUES('" +  arr[0] + "'," + getApproved() + ",'" + getComment() + "'," + project_Id + ",'" + dateFormat.format(date) + "')";
         System.out.println("Insert Project Approval" + sql);
         stmt.executeUpdate(sql);

      }
      catch (ClassNotFoundException e)
      {
         e.printStackTrace();
      }
      finally
      {
         rs.close();
         stmt.close();
         c.close();

      }
      return null;
   }

   public ApproverEvaluation(java.lang.Long id, java.lang.String comment,
         java.lang.Boolean approved)
   {
      this.id = id;
      this.comment = comment;
      this.approved = approved;
   }

}