package com.testexample.user.loginuser;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class UserDetail implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "USERDETAIL_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "USERDETAIL_ID_SEQ", name = "USERDETAIL_ID_GENERATOR")
   private java.lang.Long id;

   private java.lang.Integer age;

   private java.lang.Integer height;

   private java.lang.Boolean eligible;

   public UserDetail()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public java.lang.Integer getHeight()
   {
      return this.height;
   }

   public void setHeight(java.lang.Integer height)
   {
      this.height = height;
   }

   public java.lang.Boolean getEligible()
   {
      return this.eligible;
   }

   public void setEligible(java.lang.Boolean eligible)
   {
      this.eligible = eligible;
   }

   public UserDetail(java.lang.Long id, java.lang.Integer age,
         java.lang.Integer height, java.lang.Boolean eligible)
   {
      this.id = id;
      this.age = age;
      this.height = height;
      this.eligible = eligible;
   }

}