package com.testexample.declare.investmentdeclare;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class InvestmentDeclare implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "INVESTMENTDECLARE_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "INVESTMENTDECLARE_ID_SEQ", name = "INVESTMENTDECLARE_ID_GENERATOR")
   private java.lang.Long id;

   private java.lang.String income_Tax_Relief_Section;

   private String investment_category;

   public InvestmentDeclare()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getIncome_Tax_Relief_Section()
   {
      //  System.out.println("In setIncome_Tax_Relief_Sectio " + tax_Relief+" getInvestment_category() ");
      return this.income_Tax_Relief_Section;
   }

   public void setIncome_Tax_Relief_Section(
         java.lang.String income_Tax_Relief_Section) throws SQLException
   {
      this.income_Tax_Relief_Section = income_Tax_Relief_Section;
      Connection c = null;
      Statement stmt = null;
      try
      {

         c = DriverManager.getConnection("jdbc:postgresql://localhost:5432/mytest", "postgres", "espl@2017");

         stmt = c.createStatement();
         String investCat = this.getInvestment_category();
         int iCatgory = Integer.parseInt(investCat);
         System.out.println("In setIncome_Tax_Relief_Sectio " + getIncome_Tax_Relief_Section() + "  getInvestment_category() " + iCatgory);
         String sql = "INSERT INTO InvestmentInstrument (investment_category_id,income_tax_relief_section)values(" + iCatgory + ",'" + getIncome_Tax_Relief_Section() + "')";

         System.out.println(sql);
         stmt.executeUpdate(sql);

      }
      catch (SQLException e)
      {
         e.printStackTrace();
      }
      finally
      {
         c.close();
         stmt.close();
      }

   }

   public java.lang.String getInvestment_category()
   {
      return this.investment_category;
   }

   public void setInvestment_category(java.lang.String investment_category)
   {
      this.investment_category = investment_category;
   }

   public InvestmentDeclare(java.lang.Long id,
         java.lang.String income_Tax_Relief_Section,
         java.lang.String investment_category)
   {
      this.id = id;
      this.income_Tax_Relief_Section = income_Tax_Relief_Section;
      this.investment_category = investment_category;
   }

}